---
# run with ansible-playbook -v -i .host.linux deploy_zbx.yaml --limit host/group
#
- hosts: all
  become: yes

  tasks:

  - name: Check folder script folder exists
    stat:
     path: "{{ zbx_scr_dir }}" 
    register: workdir
 
  - name: "echo if directory already existed"
    debug:
      msg: "Folder script folder  is already existed"
    when: workdir.stat.exists
 
  - name: "Ansible Create directory if not exists"
    file:
     path: "{{ zbx_scr_dir }}"
     state: directory
     mode: 0755
     group: root
     owner: root
    when: workdir.stat.exists == false

  - name: Copy file with owner and permissions
    copy:
      src: "{{ item }}"
      dest: "{{ zbx_scr_dir }}"
      owner: root
      group: root
      mode: '0744'
      backup: yes
      validate: ls %s
    with_items:
      - nfsio_perf.bash
      - nfsio_discovery.bash
      - rpcinfo-monitor.bash
      - rpcinfo-errcount.bash
      - rpcinfo-errdetail.bash
      - nfs_mnt_client.bash
